In [1]:
import polars as pl
from datetime import datetime
from datetime import date
from datetime import time
# Import requested libraries

In [2]:
df = pl.read_excel(r"C:\Users\LENOVO\Desktop\Data Analitika\Customer-Segmentation-and-Recommendation-System\data\raw\online_retail_.xlsx")
# Read excel file

In [3]:
df.glimpse()
# Check for general info about the dataset

Rows: 525461
Columns: 8
$ Invoice              <i64> 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489435, 489435
$ StockCode            <str> '85048', '79323P', '79323W', '22041', '21232', '22064', '21871', '21523', '22350', '22349'
$ Description          <str> '15CM CHRISTMAS GLASS BALL 20 LIGHTS', 'PINK CHERRY LIGHTS', ' WHITE CHERRY LIGHTS', 'RECORD FRAME 7" SINGLE SIZE ', 'STRAWBERRY CERAMIC TRINKET BOX', 'PINK DOUGHNUT TRINKET POT ', 'SAVE THE PLANET MUG', 'FANCY FONT HOME SWEET HOME DOORMAT', 'CAT BOWL ', 'DOG BOWL , CHASING BALL DESIGN'
$ Quantity             <i64> 12, 12, 12, 48, 24, 24, 24, 10, 12, 12
$ InvoiceDate <datetime[ms]> 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:46:00, 2009-12-01 07:46:00
$ Price                <f64> 6.95, 6.75, 6.75, 2.1, 1.25, 1.65, 1.25, 5.95, 2.55, 3.75
$ Customer ID          <i64> 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085
$ Country              <str> 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom'

In [4]:
df.is_duplicated().sum()
# Count of duplicate records

13283

In [5]:
df.null_count().sum()
# Check for null values

shape: (1, 8)
┌─────────┬───────────┬─────────────┬──────────┬─────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description ┆ Quantity ┆ InvoiceDate ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---         ┆ ---   ┆ ---         ┆ ---     │
│ u32     ┆ u32       ┆ u32         ┆ u32      ┆ u32         ┆ u32   ┆ u32         ┆ u32     │
╞═════════╪═══════════╪═════════════╪══════════╪═════════════╪═══════╪═════════════╪═════════╡
│ 10209   ┆ 0         ┆ 2928        ┆ 0        ┆ 0           ┆ 0     ┆ 107927      ┆ 0       │
└─────────┴───────────┴─────────────┴──────────┴─────────────┴───────┴─────────────┴─────────┘

In [6]:
df = df.rename({
     "Invoice" : "invoice",
    "StockCode" : "stock_code",
    "Description" : "description",
    "InvoiceDate" : "invoice_date_time",
    "Quantity" : "quantity",
    "Price" : "price",
    "Customer ID" : "customer_id",
    "Country" : "country",
}
)
# Rename columns

In [7]:
df = df.with_columns(pl.col("invoice_date_time").dt.date().alias("invoice_date"))
df = df.with_columns(pl.col("invoice_date_time").dt.time().alias("invoice_time"))

In [8]:
df.filter((pl.col("stock_code") == "22087") & (pl.col("invoice_date") == date(2009, 12, 1)))

shape: (2, 10)
┌─────────┬────────────┬─────────────────────┬──────────┬───┬─────────────┬───────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description         ┆ quantity ┆ … ┆ customer_id ┆ country   ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---                 ┆ ---      ┆   ┆ ---         ┆ ---       ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str                 ┆ i64      ┆   ┆ i64         ┆ str       ┆ date         ┆ time         │
╞═════════╪════════════╪═════════════════════╪══════════╪═══╪═════════════╪═══════════╪══════════════╪══════════════╡
│ null    ┆ 22087      ┆ PAPER BUNTING WHITE ┆ -12      ┆ … ┆ 16321       ┆ Australia ┆ 2009-12-01   ┆ 10:33:00     │
│         ┆            ┆ LACE                ┆          ┆   ┆             ┆           ┆              ┆              │
│ 489450  ┆ 22087      ┆ PAPER BUNTING WHITE ┆ 12       ┆ … ┆ 16321       ┆ Australia ┆ 2009-12-01   ┆ 10:36:00     │
│         ┆            ┆ LACE                ┆          ┆   ┆             ┆           ┆              ┆              │
└─────────┴────────────┴─────────────────────┴──────────┴───┴─────────────┴───────────┴──────────────┴──────────────┘

In [9]:
df.filter(pl.col("quantity") < 0).sort(by = "invoice_date_time", descending = False)

shape: (12_326, 10)
┌─────────┬────────────┬───────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description       ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---               ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str               ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪═══════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ null    ┆ 22087      ┆ PAPER BUNTING     ┆ -12      ┆ … ┆ 16321       ┆ Australia      ┆ 2009-12-01   ┆ 10:33:00     │
│         ┆            ┆ WHITE LACE        ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 85206A     ┆ CREAM FELT EASTER ┆ -6       ┆ … ┆ 16321       ┆ Australia      ┆ 2009-12-01   ┆ 10:33:00     │
│         ┆            ┆ EGG BASKET        ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 21895      ┆ POTTING SHED SOW  ┆ -4       ┆ … ┆ 16321       ┆ Australia      ┆ 2009-12-01   ┆ 10:33:00     │
│         ┆            ┆ 'N' GROW SET      ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 21896      ┆ POTTING SHED      ┆ -6       ┆ … ┆ 16321       ┆ Australia      ┆ 2009-12-01   ┆ 10:33:00     │
│         ┆            ┆ TWINE             ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 22083      ┆ PAPER CHAIN KIT   ┆ -12      ┆ … ┆ 16321       ┆ Australia      ┆ 2009-12-01   ┆ 10:33:00     │
│         ┆            ┆ RETRO SPOT        ┆          ┆   ┆             ┆                ┆              ┆              │
│ …       ┆ …          ┆ …                 ┆ …        ┆ … ┆ …           ┆ …              ┆ …            ┆ …            │
│ 538159  ┆ 21324      ┆ null              ┆ -18      ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:17:00     │
│ 538158  ┆ 20892      ┆ null              ┆ -32      ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:17:00     │
│ 538161  ┆ 46000S     ┆ Dotcom sales      ┆ -100     ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:25:00     │
│ 538162  ┆ 46000M     ┆ Dotcom sales      ┆ -100     ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:25:00     │
│ null    ┆ 35004B     ┆ SET OF 3 BLACK    ┆ -1       ┆ … ┆ 14031       ┆ United Kingdom ┆ 2010-12-09   ┆ 17:32:00     │
│         ┆            ┆ FLYING DUCKS      ┆          ┆   ┆             ┆                ┆              ┆              │
└─────────┴────────────┴───────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘

In [11]:
df.sort(by = "invoice_date_time", descending = False)

shape: (525_461, 10)
┌─────────┬────────────┬───────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description       ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---               ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str               ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪═══════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ 489434  ┆ 85048      ┆ 15CM CHRISTMAS    ┆ 12       ┆ … ┆ 13085       ┆ United Kingdom ┆ 2009-12-01   ┆ 07:45:00     │
│         ┆            ┆ GLASS BALL 20 L…  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 489434  ┆ 79323P     ┆ PINK CHERRY       ┆ 12       ┆ … ┆ 13085       ┆ United Kingdom ┆ 2009-12-01   ┆ 07:45:00     │
│         ┆            ┆ LIGHTS            ┆          ┆   ┆             ┆                ┆              ┆              │
│ 489434  ┆ 79323W     ┆ WHITE CHERRY      ┆ 12       ┆ … ┆ 13085       ┆ United Kingdom ┆ 2009-12-01   ┆ 07:45:00     │
│         ┆            ┆ LIGHTS            ┆          ┆   ┆             ┆                ┆              ┆              │
│ 489434  ┆ 22041      ┆ RECORD FRAME 7"   ┆ 48       ┆ … ┆ 13085       ┆ United Kingdom ┆ 2009-12-01   ┆ 07:45:00     │
│         ┆            ┆ SINGLE SIZE       ┆          ┆   ┆             ┆                ┆              ┆              │
│ 489434  ┆ 21232      ┆ STRAWBERRY        ┆ 24       ┆ … ┆ 13085       ┆ United Kingdom ┆ 2009-12-01   ┆ 07:45:00     │
│         ┆            ┆ CERAMIC TRINKET   ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ BOX               ┆          ┆   ┆             ┆                ┆              ┆              │
│ …       ┆ …          ┆ …                 ┆ …        ┆ … ┆ …           ┆ …              ┆ …            ┆ …            │
│ 538171  ┆ 22271      ┆ FELTCRAFT DOLL    ┆ 2        ┆ … ┆ 17530       ┆ United Kingdom ┆ 2010-12-09   ┆ 20:01:00     │
│         ┆            ┆ ROSIE             ┆          ┆   ┆             ┆                ┆              ┆              │
│ 538171  ┆ 22750      ┆ FELTCRAFT         ┆ 1        ┆ … ┆ 17530       ┆ United Kingdom ┆ 2010-12-09   ┆ 20:01:00     │
│         ┆            ┆ PRINCESS LOLA     ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ DOLL              ┆          ┆   ┆             ┆                ┆              ┆              │
│ 538171  ┆ 22751      ┆ FELTCRAFT         ┆ 1        ┆ … ┆ 17530       ┆ United Kingdom ┆ 2010-12-09   ┆ 20:01:00     │
│         ┆            ┆ PRINCESS OLIVIA   ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ DOLL              ┆          ┆   ┆             ┆                ┆              ┆              │
│ 538171  ┆ 20970      ┆ PINK FLORAL       ┆ 2        ┆ … ┆ 17530       ┆ United Kingdom ┆ 2010-12-09   ┆ 20:01:00     │
│         ┆            ┆ FELTCRAFT         ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ SHOULDER…         ┆          ┆   ┆             ┆                ┆              ┆              │
│ 538171  ┆ 21931      ┆ JUMBO STORAGE BAG ┆ 2        ┆ … ┆ 17530       ┆ United Kingdom ┆ 2010-12-09   ┆ 20:01:00     │
│         ┆            ┆ SUKI              ┆          ┆   ┆             ┆                ┆              ┆              │
└─────────┴────────────┴───────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘

In [15]:
df.filter(pl.col("customer_id").is_null())

shape: (107_927, 10)
┌─────────┬────────────┬────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description    ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---            ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str            ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ 489464  ┆ 21733      ┆ 85123a mixed   ┆ -96      ┆ … ┆ null        ┆ United Kingdom ┆ 2009-12-01   ┆ 10:52:00     │
│ 489463  ┆ 71477      ┆ short          ┆ -240     ┆ … ┆ null        ┆ United Kingdom ┆ 2009-12-01   ┆ 10:52:00     │
│ 489467  ┆ 85123A     ┆ 21733 mixed    ┆ -192     ┆ … ┆ null        ┆ United Kingdom ┆ 2009-12-01   ┆ 10:53:00     │
│ 489521  ┆ 21646      ┆ null           ┆ -50      ┆ … ┆ null        ┆ United Kingdom ┆ 2009-12-01   ┆ 11:44:00     │
│ 489525  ┆ 85226C     ┆ BLUE PULL BACK ┆ 1        ┆ … ┆ null        ┆ United Kingdom ┆ 2009-12-01   ┆ 11:49:00     │
│         ┆            ┆ RACING CAR     ┆          ┆   ┆             ┆                ┆              ┆              │
│ …       ┆ …          ┆ …              ┆ …        ┆ … ┆ …           ┆ …              ┆ …            ┆ …            │
│ 538159  ┆ 21324      ┆ null           ┆ -18      ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:17:00     │
│ 538158  ┆ 20892      ┆ null           ┆ -32      ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:17:00     │
│ 538160  ┆ 20956      ┆ null           ┆ 288      ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:18:00     │
│ 538161  ┆ 46000S     ┆ Dotcom sales   ┆ -100     ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:25:00     │
│ 538162  ┆ 46000M     ┆ Dotcom sales   ┆ -100     ┆ … ┆ null        ┆ United Kingdom ┆ 2010-12-09   ┆ 17:25:00     │
└─────────┴────────────┴────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘

In [17]:
df.filter(df.is_duplicated())

shape: (13_283, 10)
┌─────────┬────────────┬───────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description       ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---               ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str               ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪═══════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ 489517  ┆ 21913      ┆ VINTAGE SEASIDE   ┆ 1        ┆ … ┆ 16329       ┆ United Kingdom ┆ 2009-12-01   ┆ 11:34:00     │
│         ┆            ┆ JIGSAW PUZZLES    ┆          ┆   ┆             ┆                ┆              ┆              │
│ 489517  ┆ 21912      ┆ VINTAGE SNAKES &  ┆ 1        ┆ … ┆ 16329       ┆ United Kingdom ┆ 2009-12-01   ┆ 11:34:00     │
│         ┆            ┆ LADDERS           ┆          ┆   ┆             ┆                ┆              ┆              │
│ 489517  ┆ 21821      ┆ GLITTER STAR      ┆ 1        ┆ … ┆ 16329       ┆ United Kingdom ┆ 2009-12-01   ┆ 11:34:00     │
│         ┆            ┆ GARLAND WITH      ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ BELL…             ┆          ┆   ┆             ┆                ┆              ┆              │
│ 489517  ┆ 22319      ┆ HAIRCLIPS FORTIES ┆ 12       ┆ … ┆ 16329       ┆ United Kingdom ┆ 2009-12-01   ┆ 11:34:00     │
│         ┆            ┆ FABRIC ASSOR…     ┆          ┆   ┆             ┆                ┆              ┆              │
│ 489517  ┆ 22130      ┆ PARTY CONE        ┆ 6        ┆ … ┆ 16329       ┆ United Kingdom ┆ 2009-12-01   ┆ 11:34:00     │
│         ┆            ┆ CHRISTMAS         ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ DECORATIO…        ┆          ┆   ┆             ┆                ┆              ┆              │
│ …       ┆ …          ┆ …                 ┆ …        ┆ … ┆ …           ┆ …              ┆ …            ┆ …            │
│ 538155  ┆ 21907      ┆ I'M ON HOLIDAY    ┆ 1        ┆ … ┆ 16907       ┆ United Kingdom ┆ 2010-12-09   ┆ 16:52:00     │
│         ┆            ┆ METAL SIGN        ┆          ┆   ┆             ┆                ┆              ┆              │
│ 538166  ┆ 21915      ┆ RED  HARMONICA IN ┆ 5        ┆ … ┆ 17965       ┆ United Kingdom ┆ 2010-12-09   ┆ 18:09:00     │
│         ┆            ┆ BOX               ┆          ┆   ┆             ┆                ┆              ┆              │
│ 538166  ┆ 21915      ┆ RED  HARMONICA IN ┆ 5        ┆ … ┆ 17965       ┆ United Kingdom ┆ 2010-12-09   ┆ 18:09:00     │
│         ┆            ┆ BOX               ┆          ┆   ┆             ┆                ┆              ┆              │
│ 538168  ┆ 22739      ┆ RIBBON REEL       ┆ 5        ┆ … ┆ 14702       ┆ United Kingdom ┆ 2010-12-09   ┆ 19:23:00     │
│         ┆            ┆ CHRISTMAS SOCK    ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ BAU…              ┆          ┆   ┆             ┆                ┆              ┆              │
│ 538168  ┆ 22739      ┆ RIBBON REEL       ┆ 5        ┆ … ┆ 14702       ┆ United Kingdom ┆ 2010-12-09   ┆ 19:23:00     │
│         ┆            ┆ CHRISTMAS SOCK    ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ BAU…              ┆          ┆   ┆             ┆                ┆              ┆              │
└─────────┴────────────┴───────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘